version: '3.8'

name: nginx-proxy-manager

volumes:
  data-npm:
  letsencrypt-npm:
  mariadb-npm-data:

networks:
  frontend-global_network:
    external: true
  backend-global_network:
    external: true
  npm_network:

services:
  npm:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '5790:81' # Admin Web Port
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "mariadb-npm"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - data-npm:/data
      - letsencrypt-npm:/etc/letsencrypt
    depends_on:
      - mariadb-npm
    networks:
      - frontend-global_network
      - npm_network
    

  mariadb-npm:
    container_name: mariadb-npm
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - mariadb-npm-data:/var/lib/mysql
    networks:
      - npm_network