version: "3"

networks:
  frontend-global_network:
    external: true

volumes:
  vaultwarden-data:

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
     - 4987:80
    volumes:
     - vaultwarden-data:/data:rw
    environment:
     - WEBSOCKET_ENABLED=true
     - SIGNUPS_ALLOWED=false
    networks:
      - frontend-global_network

#uncomment below network part if you are using Nginx Proxy Manager, or you can remove the same
#networks:
#  default:
#    external:
#      name: nginx-proxy-network
