version: "3"

networks:
  frontend-global_network:
    external: true

volumes:
  vaultwarden-data:

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    expose:
      - 80
    volumes:
     - vaultwarden-data:/data:rw
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=true 
      - TZ=Europe/Moscow
    networks:
      - frontend-global_network