version: "3"

name: nextcloud

volumes:
  nextcloud-data:
  nextcloud-db:
  nextcloud-cache:

networks:
  nginx-proxy-manager_network:
    external: true
  backend:

services:
  nextcloud:
    image: nextcloud
    restart: always
    volumes:
      - nextcloud-data:/var/www/html
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    networks:
      - nginx-proxy-manager_network
      - backend
    expose:
      - "80"

  postgres:
    container_name: postgres-nextcloud
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    restart: unless-stopped
    volumes:
      - nextcloud-db:/var/lib/postgresql/data
    networks:
      - backend
    expose:
      - "5432"

  redis:
    container_name: redis-nextcloud
    image: redis:alpine
    restart: unless-stopped
    networks:
      - backend
    expose:
      - "6379"
    volumes:
      - nextcloud-cache:/data